# SPDX-FileCopyrightText: 2026 Luis Llana <luis.llana.diaz@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-26 12:38

import artworks.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('lord', 'Del Señor'), ('mary', 'De la Virgen María'), ('saint', 'Santo o santa'), ('other', 'Otra')], default='saint', max_length=10, verbose_name='tipo')),
                ('rank', models.CharField(choices=[('solemnity', 'Solemnidad'), ('feast', 'Fiesta'), ('memorial', 'Memoria obligatoria'), ('optional', 'Memoria libre'), ('other', 'Otra')], default='memorial', max_length=10, verbose_name='grado')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'enero'), (2, 'febrero'), (3, 'marzo'), (4, 'abril'), (5, 'mayo'), (6, 'junio'), (7, 'julio'), (8, 'agosto'), (9, 'septiembre'), (10, 'octubre'), (11, 'noviembre'), (12, 'diciembre')], null=True, verbose_name='mes')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día')),
                ('movable', models.CharField(blank=True, choices=[('baptism', 'Bautismo del Señor'), ('ash_wednesday', 'Miércoles de Ceniza'), ('palm_sunday', 'Domingo de Ramos'), ('holy_thursday', 'Jueves Santo'), ('good_friday', 'Viernes Santo'), ('holy_saturday', 'Sábado Santo'), ('easter_sunday', 'Domingo de Resurrección'), ('divine_mercy', 'Domingo de la Divina Misericordia'), ('ascension', 'Ascensión del Señor'), ('pentecost', 'Pentecostés'), ('mary_mother_church', 'Bienaventurada Virgen María, Madre de la Iglesia'), ('christ_high_priest', 'Jesucristo, Sumo y Eterno Sacerdote'), ('trinity', 'Santísima Trinidad'), ('corpus_christi', 'Santísimo Cuerpo y Sangre de Cristo'), ('sacred_heart', 'Sagrado Corazón de Jesús'), ('immaculate_heart', 'Inmaculado Corazón de la Virgen María'), ('christ_king', 'Jesucristo, Rey del Universo'), ('first_advent', 'Primer domingo de Adviento'), ('holy_family', 'Sagrada Familia')], help_text='Para fiestas que cambian de fecha cada año (se calculan a partir de la Pascua).', max_length=30, verbose_name='fiesta móvil')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'celebración',
                'verbose_name_plural': 'calendario de celebraciones',
                'ordering': ['month', 'day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='día')),
                ('requests', models.PositiveIntegerField(default=0, verbose_name='peticiones')),
                ('clients', models.PositiveIntegerField(default=0, verbose_name='equipos distintos')),
            ],
            options={
                'verbose_name': 'estadística diaria',
                'verbose_name_plural': 'estadísticas diarias',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='MetadataKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'tipo de dato adicional',
                'verbose_name_plural': 'tipos de datos adicionales',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPEG o PNG. Solo la obra, sin marcos ni fondos añadidos.', upload_to='artworks/%Y/', validators=[artworks.validators.validate_image], verbose_name='imagen')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='título')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='autor')),
                ('year', models.CharField(blank=True, help_text='Texto libre: «1426», «c. 1450», «1450–1455»…', max_length=100, verbose_name='año')),
                ('description', models.TextField(blank=True, help_text='Qué aparece en la obra y cualquier explicación útil.', verbose_name='comentario')),
                ('source_url', models.URLField(blank=True, help_text='Dirección de la página de donde se ha obtenido la imagen.', max_length=500, verbose_name='procedencia')),
                ('license', models.CharField(blank=True, help_text='Por ejemplo: «Dominio público», «CC0», «CC BY 4.0».', max_length=200, verbose_name='licencia')),
                ('approved', models.BooleanField(default=False, verbose_name='aprobada')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprobada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificada el')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='aprobada por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
                'ordering': ['-created_at'],
                'permissions': [('approve_artwork', 'Puede aprobar obras')],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='artworks.artwork')),
            ],
            options={
                'verbose_name': 'acceso',
                'verbose_name_plural': 'accesos',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('season', 'Tiempo litúrgico'), ('celebration', 'Celebración (del Señor, de la Virgen…)'), ('saint', 'Santo del día'), ('yearly_date', 'Fecha de todos los años'), ('date', 'Fecha concreta'), ('any', 'Cualquier día (de reserva)')], max_length=20, verbose_name='cuándo')),
                ('season', models.CharField(blank=True, choices=[('advent', 'Adviento'), ('christmas', 'Navidad'), ('lent', 'Cuaresma'), ('holy_week', 'Semana Santa'), ('easter', 'Pascua'), ('ordinary', 'Tiempo ordinario')], max_length=20, verbose_name='tiempo litúrgico')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'enero'), (2, 'febrero'), (3, 'marzo'), (4, 'abril'), (5, 'mayo'), (6, 'junio'), (7, 'julio'), (8, 'agosto'), (9, 'septiembre'), (10, 'octubre'), (11, 'noviembre'), (12, 'diciembre')], null=True, verbose_name='mes')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='día')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='artworks.artwork')),
                ('celebration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='artworks.celebration', verbose_name='celebración o santo')),
            ],
            options={
                'verbose_name': 'cuándo se muestra',
                'verbose_name_plural': 'cuándo se muestra (basta con que se cumpla una)',
            },
        ),
        migrations.CreateModel(
            name='ArtworkMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='valor')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='artworks.artwork')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artworks.metadatakey', verbose_name='dato')),
            ],
            options={
                'verbose_name': 'dato adicional',
                'verbose_name_plural': 'otros datos',
                'constraints': [models.UniqueConstraint(fields=('artwork', 'key'), name='unique_metadata_per_artwork')],
            },
        ),
    ]
