# SPDX-FileCopyrightText: 2026 Luis Llana <luis.llana.diaz@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-26 15:16

import artworks.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial_celebrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'verbose_name': 'access', 'verbose_name_plural': 'accesses'},
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at'], 'permissions': [('approve_artwork', 'Can approve artworks')], 'verbose_name': 'artwork', 'verbose_name_plural': 'artworks'},
        ),
        migrations.AlterModelOptions(
            name='artworkmetadata',
            options={'verbose_name': 'additional data', 'verbose_name_plural': 'other data'},
        ),
        migrations.AlterModelOptions(
            name='celebration',
            options={'ordering': ['month', 'day', 'name'], 'verbose_name': 'celebration', 'verbose_name_plural': 'calendar of celebrations'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'when it is shown', 'verbose_name_plural': 'when it is shown (it is enough to meet one)'},
        ),
        migrations.AlterModelOptions(
            name='dailystatistic',
            options={'ordering': ['-day'], 'verbose_name': 'daily statistic', 'verbose_name_plural': 'daily statistics'},
        ),
        migrations.AlterModelOptions(
            name='metadatakey',
            options={'ordering': ['order', 'name'], 'verbose_name': 'kind of additional data', 'verbose_name_plural': 'kinds of additional data'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='author',
            field=models.CharField(blank=True, max_length=300, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, help_text='What the artwork shows and any useful explanation.', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(help_text='JPEG or PNG. Only the artwork, without added frames or backgrounds.', upload_to='artworks/%Y/', validators=[artworks.validators.validate_image], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='license',
            field=models.CharField(blank=True, help_text='For example: “Public domain”, “CC0”, “CC BY 4.0”.', max_length=200, verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='source_url',
            field=models.URLField(blank=True, help_text='Address of the page the image was taken from.', max_length=500, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.CharField(blank=True, help_text='Free text: “1426”, “c. 1450”, “1450–1455”…', max_length=100, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='artworkmetadata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artworks.metadatakey', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='artworkmetadata',
            name='value',
            field=models.CharField(max_length=500, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='kind',
            field=models.CharField(choices=[('lord', 'Of the Lord'), ('mary', 'Of the Virgin Mary'), ('saint', 'Saint'), ('other', 'Other')], default='saint', max_length=10, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='movable',
            field=models.CharField(blank=True, choices=[('baptism', 'Baptism of the Lord'), ('ash_wednesday', 'Ash Wednesday'), ('palm_sunday', 'Palm Sunday'), ('holy_thursday', 'Holy Thursday'), ('good_friday', 'Good Friday'), ('holy_saturday', 'Holy Saturday'), ('easter_sunday', 'Easter Sunday'), ('divine_mercy', 'Divine Mercy Sunday'), ('ascension', 'Ascension of the Lord'), ('pentecost', 'Pentecost'), ('mary_mother_church', 'Mary, Mother of the Church'), ('christ_high_priest', 'Christ the Eternal High Priest'), ('trinity', 'Most Holy Trinity'), ('corpus_christi', 'Corpus Christi'), ('sacred_heart', 'Sacred Heart of Jesus'), ('immaculate_heart', 'Immaculate Heart of Mary'), ('christ_king', 'Christ the King'), ('first_advent', 'First Sunday of Advent'), ('holy_family', 'Holy Family')], help_text='For celebrations whose date changes every year (computed from Easter).', max_length=30, verbose_name='movable celebration'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='rank',
            field=models.CharField(choices=[('solemnity', 'Solemnity'), ('feast', 'Feast'), ('memorial', 'Memorial'), ('optional', 'Optional memorial'), ('other', 'Other')], default='memorial', max_length=10, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='celebration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='artworks.celebration', verbose_name='celebration or saint'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='season',
            field=models.CharField(blank=True, choices=[('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('holy_week', 'Holy Week'), ('easter', 'Easter'), ('ordinary', 'Ordinary Time')], max_length=20, verbose_name='liturgical season'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(choices=[('season', 'Liturgical season'), ('celebration', 'Celebration (of the Lord, of the Virgin…)'), ('saint', 'Saint of the day'), ('yearly_date', 'Date of every year'), ('date', 'Specific date'), ('any', 'Any day (reserve)')], max_length=20, verbose_name='when'),
        ),
        migrations.AlterField(
            model_name='dailystatistic',
            name='clients',
            field=models.PositiveIntegerField(default=0, verbose_name='different computers'),
        ),
        migrations.AlterField(
            model_name='dailystatistic',
            name='day',
            field=models.DateField(unique=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='dailystatistic',
            name='requests',
            field=models.PositiveIntegerField(default=0, verbose_name='requests'),
        ),
        migrations.AlterField(
            model_name='metadatakey',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='metadatakey',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
    ]
