# SPDX-FileCopyrightText: 2026 Luis Llana <luis.llana.diaz@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_english_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebration',
            name='name_es',
            field=models.CharField(blank=True, help_text='Shown when the site is in Spanish (if empty, the name is used).', max_length=200, verbose_name='name in Spanish'),
        ),
    ]
