# SPDX-FileCopyrightText: 2026 Luis Llana <luis.llana.diaz@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-28 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_spanish_celebration_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Language code: “es”, “en”, “fr”, “pt-br”…', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]{2,3}(-[a-z0-9]{2,8})?$', 'Use a code such as “es”, “en” or “pt-br”.')], verbose_name='code')),
                ('name', models.CharField(help_text='Name of the language in that language: “Español”, “English”…', max_length=100, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_default', models.BooleanField(default=False, help_text='Used when the application does not ask for a language or asks for one that is not available.', verbose_name='default')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='artworkmetadata',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artworks.language', verbose_name='language'),
        ),
        migrations.CreateModel(
            name='ArtworkTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='author')),
                ('year', models.CharField(blank=True, help_text='Free text: “1426”, “c. 1450”, “1450–1455”…', max_length=100, verbose_name='year')),
                ('description', models.TextField(blank=True, help_text='What the artwork shows and any useful explanation.', verbose_name='comment')),
                ('license', models.CharField(blank=True, help_text='For example: “Public domain”, “CC0”, “CC BY 4.0”.', max_length=200, verbose_name='license')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.artwork')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artworks.language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'texts in a language',
                'verbose_name_plural': 'texts (one block per language)',
                'ordering': ['language__order', 'language__code'],
                'constraints': [models.UniqueConstraint(fields=('artwork', 'language'), name='unique_translation_per_language')],
            },
        ),
        migrations.CreateModel(
            name='MetadataKeyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='artworks.metadatakey')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artworks.language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'name in a language',
                'verbose_name_plural': 'names in each language',
                'constraints': [models.UniqueConstraint(fields=('key', 'language'), name='unique_key_name_per_language')],
            },
        ),
    ]
