# SPDX-FileCopyrightText: 2026 Luis Llana <luis.llana.diaz@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_existing_texts_to_spanish'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artworkmetadata',
            name='unique_metadata_per_artwork',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='author',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='license',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='year',
        ),
        migrations.AlterField(
            model_name='artworkmetadata',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artworks.language', verbose_name='language'),
        ),
        migrations.AddConstraint(
            model_name='artworkmetadata',
            constraint=models.UniqueConstraint(fields=('artwork', 'key', 'language'), name='unique_metadata_per_language'),
        ),
    ]
